import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './footer/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Investra',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Footer/>
      </body>
    </html>
  )
}
