// Import the 'Inter' font from Google Fonts using Next.js's built-in font optimization utility.
import { Inter } from 'next/font/google'
// Import the global CSS file for styling the application.
import './globals.css'

// Initialize the 'Inter' font with the Latin subset. This ensures that only the Latin characters
// are loaded, optimizing the font loading performance.
const inter = Inter({ subsets: ['latin'] })

// Metadata for the web application, including title and description. This data will be used 
// in the HTML <head> for SEO, social sharing, etc.
export const metadata = {
  title: 'Investra',
  description: 'Generated by create next app',
}
// The RootLayout component defines the structure of the app’s root HTML layout.
// The `children` prop represents the content that will be dynamically rendered in each page.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>    {/* The 'children' represent the content rendered on each page */}
    </html>
  )
}
